### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by Jeniczech** [tcql/node-yesno#6] opened 2019-03-11 13:14 UTC
Hello there, I am just wondering whether it is possible to ask multiple questions in the console? I have the following code but it prompts both questions at the same time:

const bootstrap = require('yesno');
const materialCss = require('yesno');

bootstrap.ask('Would you like to install Bootstrap?', true, function (ok) {
  if (ok) {
    console.log("Yay!");
  } else {
    console.log("Nope.");
  }
});

materialCss.ask('Would you like to install Material CSS?', true, function (ok) {
  if (ok) {
    console.log("Yay!");
  } else {
    console.log("Nope.");
  }
});

The output is: Would you like to install Bootstrap? Would you like to install Material CSS?

**Comment by mreinstein** [comment] 2019-07-26 17:40
duplicate of #7

**Closed as completed by mreinstein** 2019-07-26 17:40 UTC

**Comment by mreinstein** [comment] 2019-07-26 23:08
this is now possible as of v0.2.1. Or if you are using node versions 8+ you can use v0.3.0
